### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kartikmohta** [ros/executive_smach#44]
Can we have a new release of the package? It has been more than two years since v2.0.0 and there are a lot of fixes which would be good to have in the released version (at least for ROS kinetic).

**Comment by HWiese1980** [comment]
Totally agree!

**Comment by falkoschindler** [comment]
I discovered smach a few days ago and started to migrate my robot system towards this state machine. Especially the introspection capabilities via smach_viewer seamed convincing. But I just noticed that in Kinetic you need to build smach_viewer from source, which is rather difficult, since it requires wxPython 2.8, which isn't available in Ubuntu 16.04. Updating smach and related packages to run on current ROS and Linux distributions would be awesome!

**Comment by 130s** [comment]
+1 

If current maintainer is unable to respond, I'm happy to co-maintain for at least release tasks. If I won't hear back for a week or so then I'll contact `ros` Github organization admins.

**Comment by 130s** [comment]
As I mentioned https://github.com/ros/executive_smach/issues/44#issuecomment-300032706 I'm willing to help release task.

@ros/ros_comm-maintainers Could any of you give me a write access to this repo and [gbp repo](https://github.com/ros-gbp/executive_smach-release)?

**Comment by dirk-thomas** [comment]
> Could any of you give me a write access to this repo and gbp repo?

Done.

**Comment by 130s** [comment]
Thanks @dirk-thomas.

**Comment by orzechow** [comment]
@130s Nice to finally see an active smach maintainer again, thanks for the effort!

**Comment by 130s** [comment]
Done 
I https://github.com/ros/rosdistro/pull/15199
J https://github.com/ros/rosdistro/pull/15198
K https://github.com/ros/rosdistro/pull/15200
L https://github.com/ros/rosdistro/pull/15197
